# Generated by Django 4.0.3 on 2022-03-13 18:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='This section is about me!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='About/')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Agarbatti', max_length=20, unique=True)),
                ('subtitle', models.CharField(default='Check our agarbattis', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='Category/')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The Young Baker', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='Your ocassion, our cakes!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Home/')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rose Agarbatti', max_length=100, unique=True)),
                ('subtitle', models.CharField(default='Check this product!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Product/')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('tag', models.CharField(choices=[('featured', 'featured'), ('recent', 'recent')], default='featured', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectDesign.category')),
                ('related_home', models.ForeignKey(default='kirti-agarbatti', on_delete=django.db.models.deletion.CASCADE, to='ProjectDesign.home')),
            ],
        ),
    ]
