# Generated by Django 3.2.6 on 2023-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.CharField(default='Check our cakes ', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Cakes', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Pineapple Cake', max_length=100, unique=True),
        ),
    ]
