# Generated by Django 3.2.6 on 2023-05-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0003_auto_20230507_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.URLField(default='youtube', max_length=255),
        ),
        migrations.AlterField(
            model_name='chef',
            name='subtitle',
            field=models.CharField(default='cakes!', max_length=255),
        ),
        migrations.AlterField(
            model_name='chef',
            name='title',
            field=models.CharField(default='Sanjeev', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(default='Maharaja Hotel', max_length=255, unique=True),
        ),
    ]
