# Generated by Django 3.2.5 on 2023-05-09 07:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0004_auto_20230507_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='jonny', max_length=255, unique=True)),
                ('email', models.EmailField(default='shubhamsahu1234@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91-9518519268', max_length=20)),
                ('guest_count', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='email1',
            field=models.EmailField(default='shubhamsahu1234@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='home',
            name='email2',
            field=models.EmailField(default='shubhamsahu@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='home',
            name='phone1',
            field=models.CharField(default='+91-9518519268', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='phone2',
            field=models.CharField(default='+91-9518519268', max_length=20),
        ),
    ]
